# Generated by Django 5.2.4 on 2025-07-30 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='text',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
